server:
  address: localhost
  port: 8090

  servlet:
    encoding:
      charset: UTF-8
      force-response: true

  ## DB Properties
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/hrtest?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: Hryaya123!!
    url: jdbc:h2:mem:hrtest
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
    data: classpath:db/sql/data.sql


  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    database: mysql
    database-platform: org.hibernate.dialect.H2Dialect
  ## Hibernate Properties
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
